# Generated by Django 3.1.2 on 2020-10-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalskills',
            name='person',
        ),
    ]
