# Generated by Django 3.1.2 on 2020-10-30 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_professionalskills_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalskills',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.person'),
        ),
    ]
