# Generated by Django 3.1.2 on 2020-10-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20201031_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='passing_year',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='projectorjob',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='projectorjob',
            name='end_date',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='projectorjob',
            name='start_date',
            field=models.TextField(default=''),
        ),
    ]
