# Generated by Django 3.1.2 on 2020-10-31 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20201031_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectorjob',
            name='person',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='ProjectOrJob',
        ),
    ]
