# Generated by Django 3.1.2 on 2020-10-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0008_auto_20201031_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('skillDetail', models.TextField(default='')),
                ('academic_detail', models.TextField(default='')),
                ('area_of_interest_detail', models.TextField(default='')),
                ('degree', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=100)),
                ('passing_year', models.TextField(default='')),
                ('result', models.CharField(max_length=5)),
                ('work', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.TextField(default='')),
                ('end_date', models.TextField(default='')),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
